const KEY='interpolh_ciber_v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{pcs:[1,2,3,4].map(n=>({n,start:null})),sales:[],products:[]};
let productImageData='';
state.clients=state.clients||[]; let scannerStream=null,scannerTimer=null,scannerTarget=null,creditClientId=null; const alarmedPCs=new Set();
state.products=(state.products||[]).map(p=>({...p,dept:p.dept||'Papelería'})); state.sales=state.sales||[]; state.pcs=(state.pcs||[1,2,3,4].map(n=>({n,start:null}))).map((p,i)=>({n:p.n||i+1,start:p.start||null,limit:p.limit||null,...p}));
let selected=null,startSelected=null; const $=s=>document.querySelector(s), money=n=>'$'+Number(n||0).toFixed(2);
function save(){localStorage.setItem(KEY,JSON.stringify(state));} function elapsed(start){return start?Math.max(0,Date.now()-start):0} function charge(ms){return ms?Math.ceil(ms/(30*60*1000))*4:0} function duration(ms){let sec=Math.max(0,Math.floor(ms/1000)),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return `${h} h ${String(m).padStart(2,'0')} min ${String(s).padStart(2,'0')} s`;}
function words(n){n=Math.round(Number(n||0)*100)/100;let entero=Math.floor(n),cent=Math.round((n-entero)*100);return `${numWords(entero)} pesos ${String(cent).padStart(2,'0')}/100 M.N.`.replace(/^./,c=>c.toUpperCase())}function numWords(n){if(n===0)return'cero';if(n>999999)return String(n);const u=['','uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez','once','doce','trece','catorce','quince','dieciséis','diecisiete','dieciocho','diecinueve','veinte','veintiuno','veintidós','veintitrés','veinticuatro','veinticinco','veintiséis','veintisiete','veintiocho','veintinueve'];const tens=['','','treinta','cuarenta','cincuenta','sesenta','setenta','ochenta','noventa'];const hund=['','ciento','doscientos','trescientos','cuatrocientos','quinientos','seiscientos','setecientos','ochocientos','novecientos'];if(n<30)return u[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?' y '+u[n%10]:'');if(n===100)return'cien';if(n<1000)return hund[Math.floor(n/100)]+(n%100?' '+numWords(n%100):'');if(n<2000)return'mil'+(n%1000?' '+numWords(n%1000):'');if(n<1000000)return numWords(Math.floor(n/1000))+' mil'+(n%1000?' '+numWords(n%1000):'');return String(n)}
function beepAlarm(){try{const A=window.AudioContext||window.webkitAudioContext,ctx=new A();[0,.32,.64].forEach(t=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.0001,ctx.currentTime+t);g.gain.exponentialRampToValueAtTime(.25,ctx.currentTime+t+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+t+.22);o.connect(g);g.connect(ctx.destination);o.start(ctx.currentTime+t);o.stop(ctx.currentTime+t+.24)});setTimeout(()=>ctx.close(),1400)}catch(e){}}
function checkExpiredPCs(){state.pcs.forEach(pc=>{if(pc.start&&pc.limit&&Date.now()>=pc.limit&&!alarmedPCs.has(pc.n)){alarmedPCs.add(pc.n);beepAlarm();$('#timeAlertText').textContent=`El tiempo del Equipo ${pc.n} ha terminado.`;$('#timeAlert').classList.remove('hidden')}})}
$('#dismissTimeAlert').onclick=()=>$('#timeAlert').classList.add('hidden');
async function startScanner(target){scannerTarget=target;if(!navigator.mediaDevices?.getUserMedia){return alert('Este dispositivo/navegador no permite abrir la cámara. Puedes escribir el código o usar un lector USB.')}if(!('BarcodeDetector' in window)){return alert('El escáner automático no está disponible en este navegador. Prueba Chrome en Android/PC actualizado o usa un lector USB.')}try{const formats=await BarcodeDetector.getSupportedFormats();const wanted=['ean_13','ean_8','upc_a','upc_e','code_128','code_39','qr_code'].filter(x=>formats.includes(x));const detector=new BarcodeDetector(wanted.length?{formats:wanted}:undefined);scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('#scannerVideo').srcObject=scannerStream;$('#scannerModal').classList.remove('hidden');scannerTimer=setInterval(async()=>{try{const codes=await detector.detect($('#scannerVideo'));if(codes.length){const value=codes[0].rawValue;stopScanner();if(scannerTarget==='product'){$('#pCode').value=value}else{$('#saleSearch').value=value;renderSaleProducts()}}}catch(e){}},350)}catch(e){stopScanner();alert('No fue posible abrir la cámara. Revisa el permiso de cámara y usa HTTPS al publicarlo.')}}
function stopScanner(){if(scannerTimer)clearInterval(scannerTimer);scannerTimer=null;if(scannerStream)scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null;$('#scannerVideo').srcObject=null;$('#scannerModal').classList.add('hidden')}
$('#stopScanner').onclick=stopScanner;$('#scanProductCode').onclick=()=>startScanner('product');$('#scanSaleCode').onclick=()=>startScanner('sale');
function renderPCs(){let box=$('#pcs');box.innerHTML='';state.pcs.forEach(pc=>{let ms=elapsed(pc.start),cost=charge(ms),remaining=pc.limit?pc.limit-Date.now():null,expired=remaining!==null&&remaining<=0,d=document.createElement('div');d.className='pc '+(pc.start?'busy ':'')+(expired?'expired':'');d.innerHTML=`<h2>Equipo ${pc.n}<span class="badge">${pc.start?(expired?'TIEMPO TERMINADO':'EN USO'):'LIBRE'}</span></h2>${pc.start&&pc.limit?`<div class="remaining">⏱ ${expired?'Tiempo terminado':duration(remaining)+' restantes'}</div>`:''}<div class="meta"><span>Entrada<br><b>${pc.start?new Date(pc.start).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}):'--:--'}</b></span><span>Tiempo usado<br><b>${pc.start?duration(ms):'0 h 00 min'}</b></span></div><div class="money">${money(cost)}</div><div class="pcActions">${pc.start?`<button data-act="finish" data-pc="${pc.n}" class="primary wide">Finalizar / Cobrar</button><button data-act="extend" data-pc="${pc.n}" class="extend">+ tiempo</button>`:`<button data-act="start" data-pc="${pc.n}" class="primary wide">Iniciar</button>`}<button data-act="shutdown" data-pc="${pc.n}" class="shutdown">⏻ Apagar equipo</button></div>`;box.appendChild(d)});box.querySelectorAll('button').forEach(b=>b.onclick=()=>pcAction(+b.dataset.pc,b.dataset.act));updateToday()}
function pcAction(n,act){let pc=state.pcs.find(x=>x.n===n);if(act==='shutdown')return alert(`El botón de apagado del Equipo ${n} ya quedó preparado. Para apagar físicamente la PC necesitaremos instalar el futuro Agente INTERPOLH en ese equipo.`);if(act==='extend'){let m=prompt('¿Cuántos minutos desea agregar?','5');m=+m;if(m>0){pc.limit=(pc.limit&&pc.limit>Date.now()?pc.limit:Date.now())+m*60000;save();renderPCs()}return}if(act==='start'){startSelected=pc;$('#timerTitle').textContent=`Iniciar Equipo ${n}`;$('#timerModal').classList.remove('hidden');return}selected=pc;initModalRows();$('#modalClient').value='';$('#cashReceived').value='';updateModal();$('#modal').classList.remove('hidden')}
function begin(minutes=null){if(!startSelected)return;alarmedPCs.delete(startSelected.n);startSelected.start=Date.now();startSelected.limit=minutes?Date.now()+minutes*60000:null;save();$('#timerModal').classList.add('hidden');startSelected=null;renderPCs()}
$('#freeTime').onclick=()=>begin();document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>begin(+b.dataset.min));$('#customStart').onclick=()=>{let m=+$('#customMinutes').value;if(m>0)begin(m);else alert('Escribe los minutos.')};$('#timerCancel').onclick=()=>{$('#timerModal').classList.add('hidden');startSelected=null};
function makeAmountRow(container,onChange){let row=document.createElement('div');row.className='qrow';row.innerHTML='<input type="number" min="0" step="0.50" placeholder="Escribe el subtotal, ej. 25.00"><button type="button" title="Eliminar">✕</button>';row.querySelector('input').oninput=onChange;row.querySelector('button').onclick=()=>{row.remove();onChange()};container.appendChild(row)}
function initModalRows(){let c=$('#modalRows');c.innerHTML='';for(let i=0;i<5;i++)makeAmountRow(c,updateModal)}function modalExtras(){return [...document.querySelectorAll('#modalRows input')].reduce((a,i)=>a+(+i.value||0),0)}
function updateModal(){if(!selected)return;let ms=elapsed(selected.start),base=charge(ms),extra=modalExtras(),total=base+extra;$('#modalTitle').textContent=`Finalizar Equipo ${selected.n}`;$('#modalInfo').textContent=`Tiempo consumido: ${duration(ms)}`;$('#modalBase').textContent=money(base);$('#modalExtras').textContent=money(extra);$('#modalTotal').textContent=money(total);$('#modalWords').textContent='('+words(total)+')';let rec=+$('#cashReceived').value||0;$('#changeDue').textContent=money(Math.max(0,rec-total))}
$('#cashReceived').oninput=updateModal;$('#modalAddRow').onclick=()=>makeAmountRow($('#modalRows'),updateModal);$('#cancel').onclick=()=>{$('#modal').classList.add('hidden');selected=null};
function folio(){return 'INT-'+String((state.sales.length||0)+1).padStart(6,'0')}
$('#confirm').onclick=()=>{if(!selected)return;let ms=elapsed(selected.start),base=charge(ms),extra=modalExtras(),client=$('#modalClient').value.trim()||'Público general',total=base+extra;state.sales.push({folio:folio(),at:Date.now(),type:'Ciber',detail:`Equipo ${selected.n}`,client,base,extra,total});alarmedPCs.delete(selected.n);selected.start=null;selected.limit=null;save();$('#modal').classList.add('hidden');selected=null;renderAll()};
function addQuickRow(){makeAmountRow($('#quickRows'),sumQuick)}function sumQuick(){let t=[...document.querySelectorAll('#quickRows input')].reduce((a,i)=>a+(+i.value||0),0);$('#quickTotal').textContent=money(t);$('#quickWords').textContent=t?'('+words(t)+')':'';return t}function initQuick(){$('#quickRows').innerHTML='';$('#quickClient').value='';for(let i=0;i<12;i++)addQuickRow();sumQuick()}
$('#addRow').onclick=addQuickRow;$('#clearQuick').onclick=initQuick;$('#chargeQuick').onclick=()=>{let t=sumQuick();if(t<=0)return alert('Agrega al menos un importe.');let client=$('#quickClient').value.trim()||'Público general';state.sales.push({folio:folio(),at:Date.now(),type:'Cuenta rápida',detail:'Cuenta rápida',client,base:0,extra:0,total:t});save();initQuick();renderAll();alert('Cuenta registrada: '+money(t)+'\n'+words(t))};
let cart=[];
function showProductImage(src=''){productImageData=src||'';$('#pImagePreview').src=productImageData;$('#pImagePreview').style.display=productImageData?'block':'none';$('#pImageEmpty').style.display=productImageData?'none':'block'}
function resetProductForm(){ $('#productForm').reset(); $('#pId').value=''; $('#pMin').value=3; $('#pDept').value='Papelería'; showProductImage(''); $('#productFormTitle').textContent='Alta de producto'; $('#saveProduct').textContent='Guardar producto'; $('#cancelProductEdit').style.display='none' }
function prepareProductImage(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(!file.type.startsWith('image/'))return reject(new Error('Selecciona una imagen válida.'));const r=new FileReader();r.onerror=()=>reject(new Error('No fue posible leer la imagen.'));r.onload=()=>{const im=new Image();im.onerror=()=>reject(new Error('No fue posible abrir la imagen.'));im.onload=()=>{const size=Math.min(im.width,im.height),sx=(im.width-size)/2,sy=(im.height-size)/2,c=document.createElement('canvas');c.width=800;c.height=800;c.getContext('2d').drawImage(im,sx,sy,size,size,0,0,800,800);resolve(c.toDataURL('image/jpeg',.78))};im.src=r.result};r.readAsDataURL(file)})}
$('#pImage').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{showProductImage(await prepareProductImage(file))}catch(err){alert(err.message);e.target.value=''}});$('#removeProductImage').onclick=()=>{showProductImage('');$('#pImage').value=''};
$('#productForm').onsubmit=e=>{e.preventDefault();let id=$('#pId').value,code=$('#pCode').value.trim(),name=$('#pName').value.trim(),sell=+$('#pSell').value,stock=+$('#pStock').value,min=+$('#pMin').value,dept=$('#pDept').value||'Papelería';if(!name||sell<0)return;let duplicate=state.products.find(p=>(p.code||'')&&code&&p.code.toLowerCase()===code.toLowerCase()&&String(p.id)!==String(id));if(duplicate)return alert('Ya existe un producto con ese código.');let data={code,name,dept,desc:$('#pDesc').value.trim(),buy:+$('#pBuy').value||0,sell,stock,min,image:productImageData||''};if(id){let p=state.products.find(x=>String(x.id)===String(id));if(p)Object.assign(p,data)}else state.products.push({id:Date.now(),...data});save();resetProductForm();renderProducts();renderSaleProducts();updateToday()};
$('#cancelProductEdit').onclick=resetProductForm; $('#productSearch').oninput=renderProducts;
function renderProducts(){let q=($('#productSearch').value||'').toLowerCase(),box=$('#products'),ps=state.products.filter(p=>!q||p.name.toLowerCase().includes(q)||(p.code||'').toLowerCase().includes(q)||(p.dept||'').toLowerCase().includes(q));box.innerHTML=ps.length?ps.map(p=>`<div class="product ${p.stock<=p.min?'low':''}"><div class="productInfo">${p.image?`<img class="productThumb" src="${p.image}" alt="">`:''}<div><strong>${escHtml(p.name)}</strong><span class="deptTag">${escHtml(p.dept||'Papelería')}</span><small>${p.code?'Código: '+escHtml(p.code)+' · ':''}${money(p.sell)} · Stock: ${p.stock}${p.stock<=p.min?' · ⚠️ EXISTENCIA BAJA':''}</small><small>${escHtml(p.desc||'')}</small></div></div><div class="productActions"><button data-edit-product="${p.id}">Editar</button><button class="danger" data-delete-product="${p.id}">Eliminar</button></div></div>`).join(''):'<div class="notice">No hay productos registrados.</div>';box.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(b.dataset.editProduct));box.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct))}
function editProduct(id){let p=state.products.find(x=>String(x.id)===String(id));if(!p)return;$('#pId').value=p.id;$('#pCode').value=p.code||'';$('#pName').value=p.name||'';$('#pDept').value=p.dept||'Papelería';$('#pDesc').value=p.desc||'';$('#pBuy').value=p.buy||0;$('#pSell').value=p.sell||0;$('#pStock').value=p.stock||0;$('#pMin').value=p.min??3;showProductImage(p.image||'');$('#productFormTitle').textContent='Modificar producto';$('#saveProduct').textContent='Guardar cambios';$('#cancelProductEdit').style.display='inline-block';window.scrollTo({top:0,behavior:'smooth'})}
function deleteProduct(id){let p=state.products.find(x=>String(x.id)===String(id));if(!p)return;if(!confirm(`¿Eliminar el producto "${p.name}"?\n\nEsta acción no borra las ventas anteriores.`))return;state.products=state.products.filter(x=>String(x.id)!==String(id));cart=cart.filter(x=>String(x.id)!==String(id));save();renderProducts();renderSaleProducts();renderCart();updateToday()}
function escHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#saleSearch').oninput=renderSaleProducts;
function renderSaleProducts(){let q=($('#saleSearch').value||'').trim().toLowerCase(),box=$('#saleProducts');let ps=state.products.filter(p=>!q||p.name.toLowerCase().includes(q)||(p.code||'').toLowerCase().includes(q)||(p.dept||'').toLowerCase().includes(q));if(q){let exact=ps.find(p=>(p.code||'').toLowerCase()===q);if(exact&&exact.stock>0){addToCart(exact.id);$('#saleSearch').value='';q='';ps=state.products}}box.innerHTML=ps.length?ps.slice(0,30).map(p=>`<div class="salePick"><div class="productInfo">${p.image?`<img class="productThumb" src="${p.image}" alt="">`:''}<div><strong>${escHtml(p.name)}</strong><span class="deptTag">${escHtml(p.dept||'Papelería')}</span><small>${p.code?'Código: '+escHtml(p.code)+' · ':''}${money(p.sell)} · Existencia: ${p.stock}</small></div></div><button class="primary" data-add-cart="${p.id}" ${p.stock<=0?'disabled':''}>${p.stock>0?'Agregar':'Sin stock'}</button></div>`).join(''):'<div class="notice">No se encontraron productos.</div>';box.querySelectorAll('[data-add-cart]').forEach(b=>b.onclick=()=>addToCart(b.dataset.addCart))}
function addToCart(id){let p=state.products.find(x=>String(x.id)===String(id));if(!p||p.stock<=0)return alert('Producto sin existencia.');let row=cart.find(x=>String(x.id)===String(id));if(row){if(row.qty>=p.stock)return alert('No hay más existencia disponible.');row.qty++}else cart.push({id:p.id,qty:1});renderCart()}
function renderCart(){let box=$('#cart');box.innerHTML=cart.length?cart.map(r=>{let p=state.products.find(x=>String(x.id)===String(r.id));if(!p)return'';return `<div class="cartRow"><span><b>${escHtml(p.name)}</b><small>${money(p.sell)} c/u</small></span><input type="number" min="1" max="${p.stock}" value="${r.qty}" data-cart-qty="${p.id}"><strong>${money(p.sell*r.qty)}</strong><button class="danger" data-cart-del="${p.id}">✕</button></div>`}).join(''):'<div class="notice">El carrito está vacío.</div>';box.querySelectorAll('[data-cart-qty]').forEach(i=>i.onchange=()=>{let p=state.products.find(x=>String(x.id)===String(i.dataset.cartQty)),r=cart.find(x=>String(x.id)===String(i.dataset.cartQty));let q=Math.max(1,Math.min(+i.value||1,p.stock));r.qty=q;renderCart()});box.querySelectorAll('[data-cart-del]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>String(x.id)!==String(b.dataset.cartDel));renderCart()});let t=cart.reduce((a,r)=>{let p=state.products.find(x=>String(x.id)===String(r.id));return a+(p?p.sell*r.qty:0)},0);$('#cartTotal').textContent=money(t);$('#cartWords').textContent=t?'('+words(t)+')':''}
$('#clearCart').onclick=()=>{cart=[];renderCart()};
$('#chargeCart').onclick=()=>{if(!cart.length)return alert('Agrega al menos un producto.');for(let r of cart){let p=state.products.find(x=>String(x.id)===String(r.id));if(!p||p.stock<r.qty)return alert(`Existencia insuficiente de ${p?p.name:'un producto'}.`)}let client=$('#saleClient').value.trim()||'Público general',total=0,details=[];for(let r of cart){let p=state.products.find(x=>String(x.id)===String(r.id));p.stock-=r.qty;let subtotal=p.sell*r.qty;total+=subtotal;details.push(`${p.name} x${r.qty}`)}state.sales.push({folio:folio(),at:Date.now(),type:'Papelería',detail:details.join(' · '),client,total,base:0,extra:0});save();cart=[];$('#saleClient').value='';$('#saleSearch').value='';renderAll();alert('Venta registrada: '+money(total)+'\n'+words(total))};
function clientBalance(c){return (c.movements||[]).reduce((a,m)=>a+(m.type==='cargo'?m.amount:-m.amount),0)}
function resetClientForm(){$('#clientForm').reset();$('#clientId').value='';$('#cancelClientEdit').style.display='none'}
$('#clientForm').onsubmit=e=>{e.preventDefault();let id=$('#clientId').value,name=$('#clientName').value.trim();if(!name)return;let data={name,phone:$('#clientPhone').value.trim(),note:$('#clientNote').value.trim()};if(id){let c=state.clients.find(x=>String(x.id)===String(id));if(c)Object.assign(c,data)}else state.clients.push({id:Date.now(),...data,movements:[]});save();resetClientForm();renderClients()};
$('#cancelClientEdit').onclick=resetClientForm;$('#clientSearch').oninput=renderClients;
function renderClients(){let q=($('#clientSearch').value||'').toLowerCase(),box=$('#clients'),cs=state.clients.filter(c=>!q||c.name.toLowerCase().includes(q)||(c.phone||'').includes(q));box.innerHTML=cs.length?cs.map(c=>{let bal=clientBalance(c),mov=(c.movements||[]).slice().reverse().slice(0,6).map(m=>`<small>${new Date(m.at).toLocaleDateString('es-MX')} · ${m.type==='cargo'?'Cargo':'Abono'} · ${escHtml(m.concept||'')} · ${money(m.amount)}</small>`).join('');return `<div class="clientCard"><div><strong>${escHtml(c.name)}</strong><small>${escHtml(c.phone||'Sin teléfono')} ${c.note?' · '+escHtml(c.note):''}</small><div class="creditHistory">${mov||'<small>Sin movimientos.</small>'}</div></div><div class="clientBalance"><span>Saldo</span><b>${money(bal)}</b><button class="primary" data-credit="${c.id}">Cargo / Abono</button><button data-edit-client="${c.id}">Editar</button></div></div>`}).join(''):'<div class="notice">No hay clientes de crédito registrados.</div>';box.querySelectorAll('[data-credit]').forEach(b=>b.onclick=()=>openCredit(b.dataset.credit));box.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>editClient(b.dataset.editClient))}
function editClient(id){let c=state.clients.find(x=>String(x.id)===String(id));if(!c)return;$('#clientId').value=c.id;$('#clientName').value=c.name;$('#clientPhone').value=c.phone||'';$('#clientNote').value=c.note||'';$('#cancelClientEdit').style.display='inline-block';window.scrollTo({top:0,behavior:'smooth'})}
function openCredit(id){let c=state.clients.find(x=>String(x.id)===String(id));if(!c)return;creditClientId=c.id;$('#creditTitle').textContent=`Crédito · ${c.name}`;$('#creditBalance').textContent=`Saldo actual: ${money(clientBalance(c))}`;$('#creditType').value='cargo';$('#creditConcept').value='';$('#creditAmount').value='';$('#creditModal').classList.remove('hidden')}
$('#cancelCreditMovement').onclick=()=>{$('#creditModal').classList.add('hidden');creditClientId=null};
$('#saveCreditMovement').onclick=()=>{let c=state.clients.find(x=>String(x.id)===String(creditClientId)),amount=+$('#creditAmount').value,concept=$('#creditConcept').value.trim(),type=$('#creditType').value;if(!c||amount<=0)return alert('Escribe un importe válido.');c.movements=c.movements||[];c.movements.push({id:Date.now(),at:Date.now(),type,concept:concept||(type==='cargo'?'Cargo':'Abono'),amount});save();$('#creditModal').classList.add('hidden');creditClientId=null;renderClients()};
function todaySales(){let d=new Date().toDateString();return state.sales.filter(s=>new Date(s.at).toDateString()===d)}function updateToday(){let s=todaySales(),low=state.products.filter(p=>p.stock<=p.min).length;$('#todayBusy').textContent=`${state.pcs.filter(p=>p.start).length} equipos ocupados`;$('#todaySales').textContent=`${money(s.reduce((a,x)=>a+x.total,0))} vendidos`;$('#todayLow').textContent=`${low} productos bajos`}
function renderSales(){let sales=todaySales();$('#sales').innerHTML=sales.length?sales.slice().reverse().map(s=>`<div class="sale"><b>${new Date(s.at).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})} · ${s.type}</b> — ${s.client||'Público general'} · ${s.detail}<small>${s.folio||''}</small><strong>${money(s.total)}</strong></div>`).join(''):'<div class="notice">Todavía no hay ventas registradas hoy.</div>';let total=sales.reduce((a,s)=>a+s.total,0),c=sales.filter(s=>s.type==='Ciber').reduce((a,s)=>a+s.base,0),e=sales.filter(s=>s.type==='Ciber').reduce((a,s)=>a+(s.extra||0),0),q=sales.filter(s=>s.type==='Cuenta rápida').reduce((a,s)=>a+s.total,0),p=sales.filter(s=>s.type==='Papelería').reduce((a,s)=>a+s.total,0);$('#salesTotal').textContent=money(total);$('#cutCiber').textContent=money(c);$('#cutExtras').textContent=money(e);$('#cutQuick').textContent=money(q);$('#cutPaper').textContent=money(p);$('#cutTotal').textContent=money(total);updateToday()}
function renderAll(){renderPCs();renderProducts();renderSaleProducts();renderCart();renderClients();renderSales()}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');renderAll()});function clock(){let d=new Date();$('#clockTime').textContent=d.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit',second:'2-digit'});$('#clockDate').textContent=d.toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderPCs();if(selected)updateModal();checkExpiredPCs()}setInterval(clock,1000);initQuick();renderAll();clock();
